### ISSUE TITLE
 react-native@"0.67.4"不支持

### ISSUE THREAD

**Issue by zhengzhiwu2009** [yidun/quickpass-plugin-rn#1]
react-native@"0.67.4"版本怎么支持呢？

npm install @yidun/quickpass-plugin-rn
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: areaeduapp@0.0.1
npm ERR! Found: react-native@0.67.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from @yidun/quickpass-plugin-rn@1.1.4
npm ERR! node_modules/@yidun/quickpass-plugin-rn
npm ERR!   @yidun/quickpass-plugin-rn@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by liulingfeng** [comment]
修改package.json中的rn版本即可
